
export const PHONE_SCENARIOS = [
  { q: "Do you guys carry any Ray-Ban Meta smart glasses?", a: ["Yes, we have them in stock!", "No, but we can order them for you.", "We don't carry the electronic models yet."], c: [true, true, false] },
  { q: "Is Dr. Robbins in today for exams?", a: ["Yes, she's seeing patients until 5.", "No, she's off today.", "She's only doing follow-ups today."], c: [true, true, true] },
  { q: "My dog chewed my frames, can you fix them?", a: ["Bring them in, we can try to bridge them.", "Probably not, but we can check if the lenses fit a new frame.", "No, you need a new pair completely."], c: [true, true, false] },
  { q: "Do you take VSP insurance?", a: ["Yes, we are a premier provider!", "We are out of network, but can file for you.", "No, we don't take any insurance."], c: [true, true, false] },
  { q: "How much is a basic eye exam without insurance?", a: ["It's usually around $85-110.", "It's free with a frame purchase.", "I don't know, you'll have to ask the doctor."], c: [true, true, false] },
  { q: "Can I get my PD (pupillary distance) over the phone?", a: ["We don't give that out over the phone for liability.", "Sure, let me check your file.", "We only measure that when you buy glasses."], c: [false, true, true] },
  { q: "Do you have any 'Buy One Get One' deals?", a: ["We have a second pair discount for $50 off.", "Not currently, but check our holiday specials.", "No, our prices are already low."], c: [true, true, true] },
  { q: "Are progressives better than bifocals?", a: ["They provide a smoother transition between distances.", "They look better because there's no line.", "Bifocals are easier to get used to."], c: [true, true, true] },
  { q: "Can you put new lenses in my old frames?", a: ["Yes, if the frame is in stable condition.", "Only if you bought the frame here.", "No, we only do complete sets."], c: [true, false, false] },
  { q: "My glasses are sliding down my nose, help!", a: ["Come in for a free adjustment anytime.", "You probably need a smaller frame.", "Use some tape on the bridge."], c: [true, false, false] },
  { q: "Do you sell contact lenses?", a: ["Yes, we carry all major brands.", "Only if you have a contact lens prescription.", "No, we are strictly an eyeglass shop."], c: [true, true, false] },
  { q: "Can I use my Flex Spending Account (FSA) here?", a: ["Yes, glasses and exams are eligible!", "Only if you use it before December 31st.", "No, we don't accept those cards."], c: [true, true, false] },
  { q: "What's the difference between polycarbonate and Trivex?", a: ["Trivex has better optical clarity.", "Polycarbonate is thinner for high prescriptions.", "They are exactly the same thing."], c: [true, true, false] },
  { q: "Do you have any sports goggles for basketball?", a: ["Yes, we carry Rec Specs.", "We can order impact-resistant lenses for you.", "No, we only have fashion frames."], c: [true, true, false] },
  { q: "Is a polarized lens worth it for driving?", a: ["Absolutely, it cuts glare from the road.", "Yes, it's the best for outdoor use.", "No, just get a regular tint."], c: [true, true, false] },
  { q: "Can you fax my prescription to another doctor?", a: ["Yes, we just need your verbal consent.", "We prefer you pick it up in person.", "No, that's a HIPPA violation."], c: [true, true, false] },
  { q: "Do the Ray-Ban Wayfarers come in different sizes?", a: ["Yes, they come in 50, 52, and 54mm eye sizes.", "No, it's a one-size-fits-all frame.", "They only come in Small and Large."], c: [true, false, true] },
  { q: "My vision is blurry with my new glasses, what should I do?", a: ["It takes about a week for your brain to adapt.", "Come in so we can check the alignment.", "Your prescription is probably wrong."], c: [true, true, false] },
  { q: "Do you have a lab on-site to make glasses today?", a: ["Yes, Robbie can often do single vision today.", "Only if we have the lenses in stock.", "No, everything is sent out."], c: [true, true, false] },
  { q: "What's blue light coating and do I need it?", a: ["It helps reduce eye strain from digital screens.", "It's great if you work on a computer all day.", "It's just a marketing gimmick."], c: [true, true, false] },
  { q: "Can kids get contacts?", a: ["It depends on their maturity and hygiene.", "The doctor will evaluate them during the exam.", "No, only for adults over 18."], c: [true, true, false] },
  { q: "Do you carry Oakley frames?", a: ["Yes, we have a large selection.", "No, but we have similar sports brands.", "We carry the sunglass line only."], c: [true, true, true] },
  { q: "How do I clean my AR (Anti-Reflective) lenses?", a: ["Use a microfiber cloth and lens spray.", "Use mild soap and water.", "Use your t-shirt or a paper towel."], c: [true, true, false] },
  { q: "What are 'Office Lenses'?", a: ["They are optimized for computer and desk distances.", "They are like progressives but for closer work.", "They are just clear lenses with no power."], c: [true, true, false] },
  { q: "Do you have any frames for very wide heads?", a: ["Yes, we have an 'XL' collection.", "We can adjust the temples for a wider fit.", "No, we only stock standard sizes."], c: [true, true, false] },
  { q: "Can I get dark lenses that also become clear inside?", a: ["Yes, those are called Transitions lenses.", "They react to UV light and clear up indoors.", "No, you need two separate pairs."], c: [true, true, false] },
  { q: "What is an 'Astigmatism'?", a: ["It means your eye is shaped more like a football.", "It's a common refractive error caused by an irregular cornea.", "It means you are going blind."], c: [true, true, false] },
  { q: "Are your frames under warranty?", a: ["Most have a 1-year manufacturer warranty.", "Warranty covers defects, not accidental damage.", "No, all sales are final."], c: [true, true, false] },
  { q: "Do you have a bathroom for customers?", a: ["Yes, it's right past the lab.", "Yes, ask Tracy at the front for the key.", "No, public restrooms are next door."], c: [true, true, true] },
  { q: "Can I come in just to browse?", a: ["Of course! No appointment needed for browsing.", "Yes, come check out our New Arrivals wall.", "No, you must have an appointment to enter."], c: [true, true, false] },
  { q: "Do you offer financing like CareCredit?", a: ["Yes, we accept CareCredit for exams and glasses.", "We can set up a 3-month payment plan.", "No, we require full payment upfront."], c: [true, true, false] },
  { q: "Are you closed for lunch?", a: ["No, we stay open through the day.", "We rotate lunches so someone is always here.", "Yes, we are closed from 12-1 PM."], c: [true, true, true] },
  { q: "Can I get my glasses adjusted if I didn't buy them there?", a: ["Yes, but we charge a small $10 fee.", "We can try, but we aren't liable if they break.", "No, we only touch Pal Optical frames."], c: [true, true, false] },
  { q: "Do you carry any titanium frames?", a: ["Yes, they are very lightweight and durable.", "We have several brands that use pure titanium.", "No, we only carry acetate and steel."], c: [true, true, false] },
  { q: "What is a 'Topless' or 'Semi-Rimless' frame?", a: ["The lens is held by a nylon string at the bottom.", "It looks more minimal on your face.", "It's a frame that is missing the bridge."], c: [true, true, false] },
  { q: "Do you have any 'Petite' frames for small faces?", a: ["Yes, we have a section for narrow fits.", "We can look at the bridge size to help with fit.", "No, we don't carry any small sizes."], c: [true, true, false] },
  { q: "Can I get sunglasses with my prescription?", a: ["Yes, almost any frame can be made into sunglasses.", "We offer polarized and tinted prescription lenses.", "No, you have to wear clips instead."], c: [true, true, false] },
  { q: "Do you sell eyeglass cases separately?", a: ["Yes, we have hard and soft cases for sale.", "We usually give one for free with a purchase.", "No, we don't sell accessories."], c: [true, true, false] },
  { q: "Can I pick up my wife's glasses for her?", a: ["Yes, if she gave us permission to release them.", "Yes, as long as they are paid for.", "No, the patient must be there for the fitting."], c: [true, true, false] },
  { q: "Do you have any frames with spring hinges?", a: ["Yes, most of our Modern and Enhance lines do.", "They are great for preventing the temples from stretching.", "No, those break too easily."], c: [true, true, false] },
  { q: "What are 'Clip-ons'?", a: ["Sun lenses that attach to your regular glasses.", "A great way to save money on prescription sunglasses.", "They are lenses that clip directly into your eyes."], c: [true, true, false] },
  { q: "Do you carry Michael Kors?", a: ["Yes, we have the latest collection in stock.", "No, but we have similar luxury brands.", "We are out of stock currently."], c: [true, true, true] },
  { q: "Is a 'Digital' lens better?", a: ["It provides a wider field of vision for progressives.", "It's surfaced with 0.01 diopter precision.", "It's just a fancy name for plastic."], c: [true, true, false] },
  { q: "Can I use my old lenses in a new frame?", a: ["Only if the new frame is exactly the same model.", "We could try to shape them down to a smaller frame.", "No, lenses cannot be reused in different shapes."], c: [true, true, false] },
  { q: "Do you have any aviator styles?", a: ["Yes, from Ray-Ban to Modern, we have many.", "Classic teardrop shapes are very popular right now.", "No, those are out of style."], c: [true, true, false] },
  { q: "What time do you close on Saturdays?", a: ["We are open until 1:00 PM on Saturdays.", "We are actually closed on weekends.", "Saturday hours are by appointment only."], c: [true, true, true] },
  { q: "Can you fix a lost screw?", a: ["Yes, we have a full repair kit at the desk.", "Usually a 5-minute fix while you wait.", "No, you need a whole new frame."], c: [true, true, false] },
  { q: "Do you carry the Enhance brand?", a: ["Yes, it's one of our most popular value lines.", "We just got a new shipment of Enhance frames.", "No, we dropped that brand last month."], c: [true, true, true] },
  { q: "Can I get my frame 'repainted'?", a: ["No, we don't offer frame refinishing.", "You can try a custom shop online.", "Sure, we have spray paint in the back."], c: [true, true, false] },
  { q: "Do you have any 'Magnetic' clip-ons like Chemistrie?", a: ["Yes, we can custom make them for any frame.", "They are the best custom clip-on option.", "No, I've never heard of those."], c: [true, true, false] }
];
